//go:build !ignore_autogenerated

/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package protection

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterUsageWrapper) DeepCopyInto(out *ClusterUsageWrapper) {
	*out = *in
	in.ClusterUsage.DeepCopyInto(&out.ClusterUsage)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterUsageWrapper.
func (in *ClusterUsageWrapper) DeepCopy() *ClusterUsageWrapper {
	if in == nil {
		return nil
	}
	out := new(ClusterUsageWrapper)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterUsageWrapper) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LegacyUsageWrapper) DeepCopyInto(out *LegacyUsageWrapper) {
	*out = *in
	in.Usage.DeepCopyInto(&out.Usage)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LegacyUsageWrapper.
func (in *LegacyUsageWrapper) DeepCopy() *LegacyUsageWrapper {
	if in == nil {
		return nil
	}
	out := new(LegacyUsageWrapper)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LegacyUsageWrapper) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UsageWrapper) DeepCopyInto(out *UsageWrapper) {
	*out = *in
	in.Usage.DeepCopyInto(&out.Usage)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UsageWrapper.
func (in *UsageWrapper) DeepCopy() *UsageWrapper {
	if in == nil {
		return nil
	}
	out := new(UsageWrapper)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UsageWrapper) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
