/*
Copyright 2026 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package generator

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/printer"
	"go/token"
	"io/fs"
	"path/filepath"
	"slices"
	"strings"
	"sync"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/oapi-codegen/v2/pkg/codegen"
	"github.com/spf13/afero"
	"golang.org/x/tools/go/ast/astutil"
	extv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/kube-openapi/pkg/spec3"
	"k8s.io/kube-openapi/pkg/validation/spec"
	"sigs.k8s.io/yaml"

	"github.com/crossplane/crossplane-runtime/v2/pkg/errors"

	xpv1 "github.com/crossplane/crossplane/apis/v2/apiextensions/v1"
	"github.com/crossplane/crossplane/v2/internal/crd"
	"github.com/crossplane/crossplane/v2/internal/schemas/runner"
)

// K8s package constants.
const (
	k8sPkgMetaV1   = "io.k8s.apimachinery.pkg.apis.meta.v1"
	k8sPkgRuntime  = "io.k8s.apimachinery.pkg.runtime"
	k8sPkgCoreV1   = "io.k8s.api.core.v1"
	k8sPkgIntStr   = "io.k8s.apimachinery.pkg.util.intstr"
	k8sPkgResource = "io.k8s.apimachinery.pkg.api.resource"
)

const goModContents = `module dev.crossplane.io/models

go 1.23
`

const goImportsTemplate = `// Package {{.PackageName}} contains generated models.
//
// Code generated by {{.ModuleName}} version {{.Version}} DO NOT EDIT.
package {{.PackageName}}

import (
	"time"

	{{- range .ExternalImports}}
	{{ . }}
	{{- end}}
	{{- range .AdditionalImports}}
	{{.Alias}} "{{.Package}}"
	{{- end}}
)

// Use time to avoid unused import errors.
var (
	_ *time.Time     = nil
)
`

type goGenerator struct{}

func (goGenerator) Language() string {
	return "go"
}

// GenerateFromCRD generates Go schemas for the CRDs in the given filesystem.
func (goGenerator) GenerateFromCRD(_ context.Context, fromFS afero.Fs, _ runner.SchemaRunner) (afero.Fs, error) {
	openAPIs, err := goCollectOpenAPIs(fromFS)
	if err != nil {
		return nil, err
	}

	if len(openAPIs) == 0 {
		return nil, nil
	}

	schemaFS, err := initializeSchemaFS()
	if err != nil {
		return nil, err
	}

	k8sSchemasByPackage := make(map[string]map[string]*spec.Schema)

	for _, oapi := range openAPIs {
		packagedSchemas := goExtractK8sSchemas(oapi.spec)
		for pkg, schemas := range packagedSchemas {
			if k8sSchemasByPackage[pkg] == nil {
				k8sSchemasByPackage[pkg] = make(map[string]*spec.Schema)
			}
			for name, schema := range schemas {
				k8sSchemasByPackage[pkg][name] = schema
			}
		}
	}

	for pkg, schemas := range k8sSchemasByPackage {
		if len(schemas) == 0 {
			continue
		}

		pkgSpec := &spec3.OpenAPI{
			Version: "3.0.0",
			Components: &spec3.Components{
				Schemas: schemas,
			},
		}

		var group, kind, version string
		if pkg == k8sPkgMetaV1 {
			group = "meta.k8s.io"
			kind = "meta"
			version = "v1"
		}

		code, err := generateGo(pkgSpec, version,
			goRenameTypes,
			goRenameEnums,
			goReplaceNumberWithInt,
			goRemoveRequired,
			goReferenceK8sTypes,
		)
		if err != nil {
			return nil, err
		}

		code, err = fixK8sTypeNames(code)
		if err != nil {
			return nil, err
		}

		code, err = removeSelfImports(code, pkg)
		if err != nil {
			return nil, err
		}

		if err := writeGoCode(schemaFS, group, kind, version, code); err != nil {
			return nil, err
		}
	}

	for _, oapi := range openAPIs {
		code, err := generateGo(oapi.spec, oapi.version,
			goRenameTypes,
			goRenameEnums,
			goReplaceNumberWithInt,
			goRemoveRequired,
			goReferenceK8sTypesForCRDs,
			goRemoveK8s,
			goKeepOnlyComponents,
			goRemoveUnions,
		)
		if err != nil {
			return nil, err
		}

		if err := writeGoCode(schemaFS, oapi.crd.Spec.Group, oapi.crd.Spec.Names.Kind, oapi.version, code); err != nil {
			return nil, err
		}
	}

	return schemaFS, nil
}

type goOpenAPI struct {
	crd     *extv1.CustomResourceDefinition
	version string
	spec    *spec3.OpenAPI
}

func goCollectOpenAPIs(fromFS afero.Fs) ([]goOpenAPI, error) { //nolint:gocognit // Hard to split up.
	crdFS := afero.NewMemMapFs()
	baseFolder := "workdir"

	if err := crdFS.MkdirAll(baseFolder, 0o755); err != nil {
		return nil, err
	}

	var openAPIs []goOpenAPI
	return openAPIs, afero.Walk(fromFS, "", func(path string, info fs.FileInfo, err error) error {
		if err != nil {
			return err
		}

		if info.IsDir() {
			return nil
		}
		ext := filepath.Ext(path)
		if ext != ".yaml" && ext != ".yml" {
			return nil
		}

		var u metav1.TypeMeta
		bs, err := afero.ReadFile(fromFS, path)
		if err != nil {
			return errors.Wrapf(err, "failed to read file %q", path)
		}
		err = yaml.Unmarshal(bs, &u)
		if err != nil {
			return errors.Wrapf(err, "failed to parse file %q", path)
		}

		switch u.GroupVersionKind().Kind {
		case xpv1.CompositeResourceDefinitionKind:
			xrPath, claimPath, err := crd.ProcessXRD(crdFS, bs, path, baseFolder)
			if err != nil {
				return err
			}

			if xrPath != "" {
				bs, err := afero.ReadFile(crdFS, xrPath)
				if err != nil {
					return errors.Wrapf(err, "failed to read file %q", path)
				}

				var c extv1.CustomResourceDefinition
				if err := yaml.Unmarshal(bs, &c); err != nil {
					return errors.Wrapf(err, "failed to unmarshal CRD file %q", path)
				}

				oapis, err := crd.ToOpenAPI(&c)
				if err != nil {
					return err
				}
				for version, oapi := range oapis {
					openAPIs = append(openAPIs, goOpenAPI{spec: oapi, version: version, crd: &c})
				}
			}
			if claimPath != "" {
				bs, err := afero.ReadFile(crdFS, claimPath)
				if err != nil {
					return errors.Wrapf(err, "failed to read file %q", path)
				}

				var c extv1.CustomResourceDefinition
				if err := yaml.Unmarshal(bs, &c); err != nil {
					return errors.Wrapf(err, "failed to unmarshal CRD file %q", path)
				}

				oapis, err := crd.ToOpenAPI(&c)
				if err != nil {
					return err
				}
				for version, oapi := range oapis {
					openAPIs = append(openAPIs, goOpenAPI{spec: oapi, version: version, crd: &c})
				}
			}

		case "CustomResourceDefinition":
			var c extv1.CustomResourceDefinition
			if err := yaml.Unmarshal(bs, &c); err != nil {
				return errors.Wrapf(err, "failed to unmarshal CRD file %q", path)
			}

			oapis, err := crd.ToOpenAPI(&c)
			if err != nil {
				return err
			}
			for version, oapi := range oapis {
				openAPIs = append(openAPIs, goOpenAPI{spec: oapi, version: version, crd: &c})
			}
		}
		return nil
	})
}

var generateGoMutex sync.Mutex //nolint:gochecknoglobals // Must be global.

func generateGo(s *spec3.OpenAPI, version string, mutators ...func(*spec3.OpenAPI)) (string, error) {
	for _, mut := range mutators {
		mut(s)
	}

	bs, err := json.Marshal(s)
	if err != nil {
		return "", errors.Wrap(err, "failed to marshal OpenAPI spec")
	}
	ld := openapi3.NewLoader()
	oapiInput, err := ld.LoadFromData(bs)
	if err != nil {
		return "", errors.Wrap(err, "failed to parse OpenAPI spec")
	}

	generateGoMutex.Lock()
	defer generateGoMutex.Unlock()
	goCode, err := codegen.Generate(oapiInput, codegen.Configuration{
		PackageName: version,
		Generate: codegen.GenerateOptions{
			Models: true,
		},
		OutputOptions: codegen.OutputOptions{
			SkipPrune:      true,
			NameNormalizer: string(codegen.NameNormalizerFunctionToCamelCaseWithInitialisms),
			SkipFmt:        true,
			UserTemplates: map[string]string{
				"imports.tmpl": goImportsTemplate,
			},
		},
	})
	if err != nil {
		return "", errors.Wrap(err, "failed to generate go code from OpenAPI schema")
	}

	goCode, err = fixMissingImports(goCode)
	if err != nil {
		return "", errors.Wrap(err, "failed to fix missing imports")
	}

	goCodeBytes, err := format.Source([]byte(goCode))
	if err != nil {
		return "", errors.Wrap(err, "failed to format go code")
	}

	return string(goCodeBytes), nil
}

func goExtractK8sSchemas(s *spec3.OpenAPI) map[string]map[string]*spec.Schema {
	ret := make(map[string]map[string]*spec.Schema)

	k8sPackages := []string{
		k8sPkgMetaV1,
		k8sPkgRuntime,
		k8sPkgCoreV1,
		k8sPkgIntStr,
		k8sPkgResource,
	}

	for _, pkg := range k8sPackages {
		ret[pkg] = make(map[string]*spec.Schema)
	}

	for name, schema := range s.Components.Schemas {
		for _, pkg := range k8sPackages {
			if strings.Contains(name, pkg) {
				ret[pkg][name] = schema
				break
			}
		}
	}

	for pkg := range ret {
		if len(ret[pkg]) == 0 {
			delete(ret, pkg)
		}
	}

	return ret
}

func writeGoCode(schemaFS afero.Fs, group, kind, version, code string) error {
	goPath := filepath.Join("models", goSchemaPath(group, kind, version))
	dir := filepath.Dir(goPath)
	if err := schemaFS.MkdirAll(dir, 0o755); err != nil {
		return errors.Wrap(err, "failed to create directory for schemas")
	}

	f, err := schemaFS.Create(goPath)
	if err != nil {
		return errors.Wrap(err, "failed to create go schema file")
	}
	if _, err := f.WriteString(code); err != nil {
		return errors.Wrap(err, "failed to write go code to file")
	}
	_ = f.Close()

	return nil
}

func goSchemaPath(group, kind, version string) string {
	if group == "meta.core.k8s.io" {
		return filepath.Join("io", "k8s", "core", "meta", version, strings.ToLower(kind)+".go")
	}

	switch group {
	case "apps", "autoscaling", "batch", "policy":
		return filepath.Join("io", "k8s", group, version, strings.ToLower(kind)+".go")
	}

	path := strings.Split(group, ".")
	slices.Reverse(path)
	path = append(path, version, strings.ToLower(kind)+".go")

	return filepath.Join(path...)
}

func goRenameTypes(s *spec3.OpenAPI) {
	for name, schema := range s.Components.Schemas {
		goName := goFixName(name)
		if goName == "" {
			delete(s.Components.Schemas, name)
		}
		goRenameSchemaType(goName, schema)
		goRenamePropertyTypes(goName, schema.Properties)
	}
}

func goRenamePropertyTypes(baseName string, props map[string]spec.Schema) {
	for name, prop := range props {
		goName := goFixName(baseName + strings.ToUpper(string(name[0])) + name[1:])

		goRenameSchemaType(goName, &prop)
		goRenamePropertyTypes(goName, prop.Properties)

		if prop.Items != nil {
			goRenameSchemaType(goName+"Item", prop.Items.Schema)
			goRenamePropertyTypes(goName+"Item", prop.Items.Schema.Properties)
		}

		props[name] = prop
	}
}

func goFixName(name string) string {
	generateGoMutex.Lock()
	defer generateGoMutex.Unlock()

	lastDot := strings.LastIndex(name, ".")
	if lastDot == -1 {
		return codegen.ToCamelCaseWithInitialisms(name)
	}
	genName := codegen.SchemaNameToTypeName(name)
	prefix := codegen.SchemaNameToTypeName(name[:lastDot])
	return codegen.ToCamelCaseWithInitialisms(strings.TrimPrefix(genName, prefix))
}

func goRenameSchemaType(name string, schema *spec.Schema) {
	schema.AddExtension("x-go-type-name", name)
	schema.AddExtension("x-oapi-codegen-only-honour-go-name", true)
}

func goRenameEnums(s *spec3.OpenAPI) {
	for name, schema := range s.Components.Schemas {
		goName := goFixName(name)
		if goName == "" {
			delete(s.Components.Schemas, name)
		}
		goRenameEnumValues(goName, schema)
		goRenamePropertyEnums(goName, schema.Properties)
	}
}

func goRenamePropertyEnums(baseName string, props map[string]spec.Schema) {
	for name, prop := range props {
		goName := goFixName(baseName + strings.ToUpper(string(name[0])) + name[1:])

		goRenameEnumValues(goName, &prop)
		goRenamePropertyEnums(goName, prop.Properties)

		if prop.Items != nil {
			goRenameEnumValues(goName+"Item", prop.Items.Schema)
			goRenamePropertyEnums(goName+"Item", prop.Items.Schema.Properties)
		}

		props[name] = prop
	}
}

func goRenameEnumValues(typeName string, schema *spec.Schema) {
	if schema.Enum == nil {
		return
	}

	newNames := make([]string, len(schema.Enum))
	for i, oldName := range schema.Enum {
		s, ok := oldName.(string)
		if !ok {
			continue
		}
		newNames[i] = typeName + s
	}

	schema.AddExtension("x-enum-varnames", newNames)
}

func goReplaceNumberWithInt(s *spec3.OpenAPI) {
	for _, schema := range s.Components.Schemas {
		goRetypeSchema(schema, "number", "int")
		goRetypeProperties(schema.Properties, "number", "int")
	}
}

func goRetypeProperties(props map[string]spec.Schema, oldType, newType string) {
	for name, prop := range props {
		goRetypeSchema(&prop, oldType, newType)
		if prop.Items != nil {
			goRetypeSchema(prop.Items.Schema, oldType, newType)
			goRetypeProperties(prop.Items.Schema.Properties, oldType, newType)
		}
		props[name] = prop
	}
}

func goRetypeSchema(schema *spec.Schema, oldType, newType string) {
	if schema.Type.Contains(oldType) {
		schema.AddExtension("x-go-type", newType)
	}
}

func goRemoveRequired(s *spec3.OpenAPI) {
	for _, schema := range s.Components.Schemas {
		schema.Required = nil
		goRemovePropertiesRequired(schema.Properties)
		if schema.Items != nil {
			goRemovePropertiesRequired(schema.Items.Schema.Properties)
		}
	}
}

func goRemovePropertiesRequired(props map[string]spec.Schema) {
	for name, prop := range props {
		prop.Required = nil
		goRemovePropertiesRequired(prop.Properties)
		if prop.Items != nil {
			prop.Items.Schema.Required = nil
			goRemovePropertiesRequired(prop.Items.Schema.Properties)
		}

		props[name] = prop
	}
}

func goReferenceK8sTypes(s *spec3.OpenAPI) {
	for _, schema := range s.Components.Schemas {
		goReferenceK8sType(schema)
		goReferenceK8sTypesProperties(schema.Properties)
	}
}

func goReferenceK8sTypesForCRDs(s *spec3.OpenAPI) {
	for _, schema := range s.Components.Schemas {
		goReferenceK8sTypeWithMetaPath(schema, false)
		goReferenceK8sTypesPropertiesWithMetaPath(schema.Properties, false)
	}
}

func goReferenceK8sType(schema *spec.Schema) {
	goReferenceK8sTypeWithMetaPath(schema, true)
}

func goReferenceK8sTypeWithMetaPath(schema *spec.Schema, useCorePath bool) {
	isK8sRef := func(ref string) bool {
		return strings.Contains(ref, k8sPkgMetaV1) ||
			strings.Contains(ref, k8sPkgCoreV1) ||
			strings.Contains(ref, k8sPkgRuntime) ||
			strings.Contains(ref, k8sPkgIntStr) ||
			strings.Contains(ref, k8sPkgResource)
	}

	ref := schema.Ref.String()
	if isK8sRef(ref) {
		tryReplaceK8sTypeWithMetaPath(schema, ref, useCorePath)
		schema.Ref = spec.Ref{}
	}

	allK8s := true
	for _, one := range schema.AllOf {
		if one.Ref.String() == "" || !isK8sRef(one.Ref.String()) {
			allK8s = false
			break
		}
	}

	if allK8s && len(schema.AllOf) > 0 {
		ref := schema.AllOf[0].Ref.String()
		tryReplaceK8sTypeWithMetaPath(schema, ref, useCorePath)
		schema.AllOf = nil
	} else {
		for i := range schema.AllOf {
			goReferenceK8sTypeWithMetaPath(&schema.AllOf[i], useCorePath)
		}
	}

	for i := range schema.OneOf {
		goReferenceK8sTypeWithMetaPath(&schema.OneOf[i], useCorePath)
	}
	for i := range schema.AnyOf {
		goReferenceK8sTypeWithMetaPath(&schema.AnyOf[i], useCorePath)
	}
}

func goReferenceK8sTypesProperties(props map[string]spec.Schema) {
	goReferenceK8sTypesPropertiesWithMetaPath(props, true)
}

func goReferenceK8sTypesPropertiesWithMetaPath(props map[string]spec.Schema, useCorePath bool) {
	for name, prop := range props {
		goReferenceK8sTypeWithMetaPath(&prop, useCorePath)
		goReferenceK8sTypesPropertiesWithMetaPath(prop.Properties, useCorePath)
		if prop.Items != nil {
			goReferenceK8sTypeWithMetaPath(prop.Items.Schema, useCorePath)
			goReferenceK8sTypesPropertiesWithMetaPath(prop.Items.Schema.Properties, useCorePath)
		}
		if prop.AdditionalProperties != nil && prop.AdditionalProperties.Schema != nil {
			goReferenceK8sTypeWithMetaPath(prop.AdditionalProperties.Schema, useCorePath)
			goReferenceK8sTypesPropertiesWithMetaPath(prop.AdditionalProperties.Schema.Properties, useCorePath)
		}

		props[name] = prop
	}
}

func tryReplaceK8sTypeWithMetaPath(schema *spec.Schema, ref string, useCorePath bool) {
	lastDot := strings.LastIndex(ref, ".")
	if lastDot == -1 {
		return
	}
	t := ref[lastDot+1:]

	metaAlias := "metacorev1"
	metaPath := "dev.crossplane.io/models/io/k8s/core/meta/v1"
	if !useCorePath {
		metaAlias = "metav1"
		metaPath = "dev.crossplane.io/models/io/k8s/meta/v1"
	}

	mapping := []struct {
		contains   string
		alias      string
		importPath string
	}{
		{k8sPkgMetaV1, metaAlias, metaPath},
		{k8sPkgCoreV1, "corev1", "dev.crossplane.io/models/io/k8s/core/v1"},
		{k8sPkgRuntime, "runtimev1", "dev.crossplane.io/models/io/k8s/runtime/v1"},
		{k8sPkgIntStr, "intstrv1", "dev.crossplane.io/models/io/k8s/util/v1"},
		{k8sPkgResource, "resourcev1", "dev.crossplane.io/models/io/k8s/resource/v1"},
	}

	for _, m := range mapping {
		if strings.Contains(ref, m.contains) {
			schema.AddExtension("x-go-type", m.alias+"."+t)
			schema.AddExtension("x-go-type-import", map[string]string{
				"path": m.importPath,
				"name": m.alias,
			})
			return
		}
	}
}

func goRemoveK8s(s *spec3.OpenAPI) {
	for name := range s.Components.Schemas {
		if strings.HasPrefix(name, k8sPkgMetaV1) ||
			strings.HasPrefix(name, k8sPkgRuntime) ||
			strings.HasPrefix(name, k8sPkgCoreV1) ||
			strings.HasPrefix(name, k8sPkgIntStr) ||
			strings.HasPrefix(name, k8sPkgResource) {
			delete(s.Components.Schemas, name)
		}
	}
}

func goKeepOnlyComponents(s *spec3.OpenAPI) {
	*s = spec3.OpenAPI{
		Version:    s.Version,
		Info:       s.Info,
		Components: s.Components,
	}
}

func goSimplifyK8sUnionTypes(s *spec3.OpenAPI) {
	if s.Components == nil || s.Components.Schemas == nil {
		return
	}

	unionTypes := []string{
		"io.k8s.apimachinery.pkg.api.resource.Quantity",
		"io.k8s.apimachinery.pkg.util.intstr.IntOrString",
	}

	for name, schema := range s.Components.Schemas {
		for _, unionType := range unionTypes {
			if strings.Contains(name, unionType) {
				if len(schema.OneOf) > 0 {
					schema.OneOf = nil
					schema.Type = spec.StringOrArray{"string"}
				}
				break
			}
		}
		goSimplifyK8sUnionProperties(schema.Properties, unionTypes)
	}
}

func goSimplifyK8sUnionProperties(props map[string]spec.Schema, unionTypes []string) {
	for name, prop := range props {
		goSimplifyK8sUnionProperties(prop.Properties, unionTypes)

		if prop.Items != nil {
			goSimplifyK8sUnionProperties(prop.Items.Schema.Properties, unionTypes)
		}

		if prop.AdditionalProperties != nil && prop.AdditionalProperties.Schema != nil {
			goSimplifyK8sUnionProperties(prop.AdditionalProperties.Schema.Properties, unionTypes)
		}

		props[name] = prop
	}
}

func goRemoveUnions(s *spec3.OpenAPI) {
	if s.Components == nil || s.Components.Schemas == nil {
		return
	}

	for _, schema := range s.Components.Schemas {
		goRemoveUnionsInSchema(schema)
		goRemoveUnionsInProperties(schema.Properties)
	}
}

func goRemoveUnionsInSchema(schema *spec.Schema) {
	if (len(schema.OneOf) > 0 || len(schema.AnyOf) > 0) && len(schema.Properties) > 0 {
		schema.OneOf = nil
		schema.AnyOf = nil
	}

	if schema.Items != nil && schema.Items.Schema != nil {
		goRemoveUnionsInSchema(schema.Items.Schema)
		goRemoveUnionsInProperties(schema.Items.Schema.Properties)
	}
}

func goRemoveUnionsInProperties(props map[string]spec.Schema) {
	for name, prop := range props {
		goRemoveUnionsInSchema(&prop)
		goRemoveUnionsInProperties(prop.Properties)

		if prop.Items != nil && prop.Items.Schema != nil {
			goRemoveUnionsInSchema(prop.Items.Schema)
			goRemoveUnionsInProperties(prop.Items.Schema.Properties)
		}

		props[name] = prop
	}
}

func goAddDefaults(s *spec3.OpenAPI) {
	if s.Components == nil || s.Components.Schemas == nil {
		return
	}

	for _, schema := range s.Components.Schemas {
		processSchemaDefaults(schema)
	}
}

func processSchemaDefaults(schema *spec.Schema) {
	rawExt, ok := schema.Extensions["x-kubernetes-group-version-kind"]
	if !ok {
		return
	}

	gvkList := extractGVKList(rawExt)
	if len(gvkList) == 0 {
		return
	}

	group, version, kind := extractGVKInfo(gvkList[0])
	apiVersion := constructAPIVersion(group, version)
	addSchemaPropertyDefaultsGo(schema, apiVersion, kind)
}

func extractGVKList(rawExt any) []map[string]any {
	var gvkList []map[string]any
	switch ext := rawExt.(type) {
	case []any:
		for _, item := range ext {
			if gvk, ok := item.(map[string]any); ok {
				gvkList = append(gvkList, gvk)
			}
		}
	case []map[string]any:
		gvkList = ext
	}
	return gvkList
}

func extractGVKInfo(gvk map[string]any) (group, version, kind string) {
	if g, ok := gvk["group"].(string); ok {
		group = g
	}
	if v, ok := gvk["version"].(string); ok {
		version = v
	}
	if k, ok := gvk["kind"].(string); ok {
		kind = k
	}
	return group, version, kind
}

func constructAPIVersion(group, version string) string {
	if group != "" {
		return group + "/" + version
	}
	return version
}

func addSchemaPropertyDefaultsGo(schema *spec.Schema, apiVersion, kind string) {
	if schema.Properties == nil {
		return
	}

	if propSchema, ok := schema.Properties["apiVersion"]; ok {
		propSchema.Default = apiVersion
		propSchema.Enum = []any{apiVersion}
		schema.Properties["apiVersion"] = propSchema
	}

	if propSchema, ok := schema.Properties["kind"]; ok {
		propSchema.Default = kind
		propSchema.Enum = []any{kind}
		schema.Properties["kind"] = propSchema
	}
}

func removeSelfImports(code string, pkg string) (string, error) {
	selfImports := map[string]struct {
		Alias, Path string
	}{
		k8sPkgMetaV1:   {"metacorev1", "dev.crossplane.io/models/io/k8s/core/meta/v1"},
		k8sPkgCoreV1:   {"corev1", "dev.crossplane.io/models/io/k8s/core/v1"},
		k8sPkgRuntime:  {"runtimev1", "dev.crossplane.io/models/io/k8s/runtime/v1"},
		k8sPkgIntStr:   {"intstrv1", "dev.crossplane.io/models/io/k8s/util/v1"},
		k8sPkgResource: {"resourcev1", "dev.crossplane.io/models/io/k8s/resource/v1"},
	}

	info, ok := selfImports[pkg]
	if !ok {
		return code, nil
	}

	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, "", code, parser.ParseComments)
	if err != nil {
		return "", errors.Wrap(err, "parsing Go code")
	}

	astutil.DeleteImport(fset, f, info.Path)
	astutil.DeleteNamedImport(fset, f, info.Alias, info.Path)

	astutil.Apply(f, nil, func(c *astutil.Cursor) bool {
		if sel, ok := c.Node().(*ast.SelectorExpr); ok {
			if pkgIdent, ok := sel.X.(*ast.Ident); ok && pkgIdent.Name == info.Alias {
				c.Replace(&ast.Ident{Name: sel.Sel.Name, NamePos: sel.Sel.NamePos})
			}
		}
		return true
	})

	var buf strings.Builder
	if err := format.Node(&buf, fset, f); err != nil {
		return "", errors.Wrap(err, "formatting Go code")
	}
	return buf.String(), nil
}

func fixMissingImports(code string) (string, error) {
	k8sImports := map[string]string{
		"metacorev1": "dev.crossplane.io/models/io/k8s/core/meta/v1",
		"metav1":     "dev.crossplane.io/models/io/k8s/meta/v1",
		"corev1":     "dev.crossplane.io/models/io/k8s/core/v1",
		"resourcev1": "dev.crossplane.io/models/io/k8s/resource/v1",
		"runtimev1":  "dev.crossplane.io/models/io/k8s/runtime/v1",
		"intstrv1":   "dev.crossplane.io/models/io/k8s/util/v1",
	}

	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, "", code, parser.ParseComments)
	if err != nil {
		return "", fmt.Errorf("parsing failed: %w", err)
	}

	needed := map[string]bool{}
	ast.Inspect(f, func(n ast.Node) bool {
		if sel, ok := n.(*ast.SelectorExpr); ok {
			if pkg, ok := sel.X.(*ast.Ident); ok {
				if _, known := k8sImports[pkg.Name]; known {
					needed[pkg.Name] = true
				}
			}
		}
		return true
	})

	for alias, path := range k8sImports {
		if !needed[alias] {
			continue
		}
		astutil.AddNamedImport(fset, f, alias, path)
	}

	var buf bytes.Buffer
	if err := printer.Fprint(&buf, fset, f); err != nil {
		return "", fmt.Errorf("printing AST failed: %w", err)
	}
	return buf.String(), nil
}

func fixK8sTypeNames(code string) (string, error) {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, "", code, parser.ParseComments)
	if err != nil {
		return "", errors.Wrap(err, "failed to parse Go code")
	}

	replacements := map[string]string{
		"IoK8SApimachineryPkgApisMetaV1Time":        "Time",
		"IoK8SApimachineryPkgApisMetaV1MicroTime":   "MicroTime",
		"IoK8SApimachineryPkgAPIResourceQuantity":   "Quantity",
		"IoK8SApimachineryPkgUtilIntstrIntOrString": "IntOrString",
	}

	ast.Inspect(f, func(n ast.Node) bool {
		if x, ok := n.(*ast.Ident); ok {
			if newName, ok := replacements[x.Name]; ok {
				x.Name = newName
			}
		}
		return true
	})

	var buf strings.Builder
	if err := format.Node(&buf, fset, f); err != nil {
		return "", errors.Wrap(err, "failed to format Go code")
	}

	return buf.String(), nil
}

// GenerateFromOpenAPI generates Go schemas for the OpenAPI docs in the given
// filesystem.
func (goGenerator) GenerateFromOpenAPI(_ context.Context, fromFS afero.Fs, _ runner.SchemaRunner) (afero.Fs, error) {
	openAPISpecs, err := collectOpenAPISpecs(fromFS)
	if err != nil {
		return nil, err
	}

	if len(openAPISpecs) == 0 {
		return nil, nil
	}

	schemaFS, err := initializeSchemaFS()
	if err != nil {
		return nil, err
	}

	if err := generateK8sSharedSchemas(openAPISpecs, schemaFS); err != nil {
		return nil, err
	}

	if err := generateModelsWithGVK(openAPISpecs, schemaFS); err != nil {
		return nil, err
	}

	return schemaFS, nil
}

func collectOpenAPISpecs(fromFS afero.Fs) ([]*spec3.OpenAPI, error) {
	var openAPISpecs []*spec3.OpenAPI

	err := afero.Walk(fromFS, "", func(path string, info fs.FileInfo, err error) error {
		if err != nil {
			return err
		}

		if info.IsDir() {
			return nil
		}

		if !strings.HasSuffix(strings.ToLower(path), ".json") {
			return nil
		}

		bs, err := afero.ReadFile(fromFS, path)
		if err != nil {
			return errors.Wrapf(err, "failed to read file %q", path)
		}

		var s spec3.OpenAPI
		if err := json.Unmarshal(bs, &s); err != nil {
			return nil //nolint:nilerr // Skip invalid files.
		}

		if s.Components == nil || len(s.Components.Schemas) == 0 {
			return nil
		}

		openAPISpecs = append(openAPISpecs, &s)
		return nil
	})

	return openAPISpecs, err
}

func initializeSchemaFS() (afero.Fs, error) {
	schemaFS := afero.NewMemMapFs()
	if err := schemaFS.Mkdir("models", 0o755); err != nil {
		return nil, errors.Wrap(err, "failed to create models directory")
	}

	modf, err := schemaFS.Create("models/go.mod")
	if err != nil {
		return nil, errors.Wrap(err, "failed to create go.mod")
	}
	if _, err := modf.WriteString(goModContents); err != nil {
		return nil, errors.Wrap(err, "failed to write go.mod")
	}

	return schemaFS, nil
}

func generateK8sSharedSchemas(openAPISpecs []*spec3.OpenAPI, schemaFS afero.Fs) error {
	k8sSchemasByPackage := make(map[string]map[string]*spec.Schema)

	for _, openAPISpec := range openAPISpecs {
		packagedSchemas := goExtractK8sSchemas(openAPISpec)
		for pkg, schemas := range packagedSchemas {
			if k8sSchemasByPackage[pkg] == nil {
				k8sSchemasByPackage[pkg] = make(map[string]*spec.Schema)
			}
			for name, schema := range schemas {
				k8sSchemasByPackage[pkg][name] = schema
			}
		}
	}

	for pkg, schemas := range k8sSchemasByPackage {
		if len(schemas) == 0 {
			continue
		}

		if err := generateK8sPackageCode(pkg, schemas, schemaFS); err != nil {
			return err
		}
	}

	return nil
}

func generateK8sPackageCode(pkg string, schemas map[string]*spec.Schema, schemaFS afero.Fs) error {
	pkgSpec := &spec3.OpenAPI{
		Version: "3.0.0",
		Components: &spec3.Components{
			Schemas: schemas,
		},
	}

	group, kind, version := getK8sPackageInfo(pkg)

	code, err := generateGo(pkgSpec, version,
		goRenameTypes,
		goRenameEnums,
		goReplaceNumberWithInt,
		goRemoveRequired,
		goSimplifyK8sUnionTypes,
		goReferenceK8sTypes,
		goAddDefaults,
	)
	if err != nil {
		return err
	}

	code, err = fixK8sTypeNames(code)
	if err != nil {
		return errors.Wrap(err, "failed to fix K8s type names")
	}
	code, err = removeSelfImports(code, pkg)
	if err != nil {
		return errors.Wrap(err, "failed to remove self imports")
	}

	return writeGoCode(schemaFS, group, kind, version, code)
}

func getK8sPackageInfo(pkg string) (group, kind, version string) {
	switch pkg {
	case k8sPkgMetaV1:
		return "meta.core.k8s.io", "meta", "v1"
	case k8sPkgRuntime:
		return "runtime.k8s.io", "runtime", "v1"
	case k8sPkgCoreV1:
		return "core.k8s.io", "core", "v1"
	case k8sPkgIntStr:
		return "util.k8s.io", "intstr", "v1"
	case k8sPkgResource:
		return "resource.k8s.io", "resource", "v1"
	default:
		return "", "", ""
	}
}

func generateModelsWithGVK(openAPISpecs []*spec3.OpenAPI, schemaFS afero.Fs) error {
	for _, openAPISpec := range openAPISpecs {
		gvkGroups := groupSchemasByGVK(openAPISpec)

		for gvkKey, schemas := range gvkGroups {
			if err := generateGVKGroupCode(gvkKey, schemas, openAPISpec, schemaFS); err != nil {
				return err
			}
		}
	}
	return nil
}

func groupSchemasByGVK(openAPISpec *spec3.OpenAPI) map[string]map[string]*spec.Schema {
	gvkGroups := make(map[string]map[string]*spec.Schema)

	for name, schema := range openAPISpec.Components.Schemas {
		gvkKey := extractGVKKey(schema)
		if gvkKey == "" {
			continue
		}

		if gvkGroups[gvkKey] == nil {
			gvkGroups[gvkKey] = make(map[string]*spec.Schema)
		}
		gvkGroups[gvkKey][name] = schema
	}

	return gvkGroups
}

func extractGVKKey(schema *spec.Schema) string {
	gvkExt, ok := schema.Extensions["x-kubernetes-group-version-kind"]
	if !ok {
		return ""
	}

	gvkList, ok := gvkExt.([]any)
	if !ok || len(gvkList) == 0 {
		return ""
	}

	gvk, ok := gvkList[0].(map[string]any)
	if !ok {
		return ""
	}

	group, ok := gvk["group"].(string)
	if !ok {
		return ""
	}

	version, ok := gvk["version"].(string)
	if !ok || version == "" {
		return ""
	}

	if group == "core" || group == "" {
		return ""
	}

	return group + "/" + version
}

func generateGVKGroupCode(gvkKey string, schemas map[string]*spec.Schema, openAPISpec *spec3.OpenAPI, schemaFS afero.Fs) error {
	parts := strings.Split(gvkKey, "/")
	group, version := parts[0], parts[1]

	kind := group
	if dotIndex := strings.Index(group, "."); dotIndex != -1 {
		kind = group[:dotIndex]
	}

	groupSpec := &spec3.OpenAPI{
		Version: "3.0.0",
		Components: &spec3.Components{
			Schemas: make(map[string]*spec.Schema),
		},
	}

	for name, schema := range schemas {
		groupSpec.Components.Schemas[name] = schema
	}

	for name, schema := range openAPISpec.Components.Schemas {
		groupSpec.Components.Schemas[name] = schema
	}

	code, err := generateGo(groupSpec, version,
		goRenameTypes,
		goRenameEnums,
		goReplaceNumberWithInt,
		goRemoveRequired,
		goReferenceK8sTypes,
		goRemoveK8s,
		goKeepOnlyComponents,
		goAddDefaults,
	)
	if err != nil {
		return err
	}

	return writeGoCode(schemaFS, group, kind, version, code)
}
